TarankoWebSite/Models/ErrorViewModel.cs
namespace TarankoWebSite.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

TarankoWebSite/Controllers/AboutController.cs
using Microsoft.AspNetCore.Mvc;

namespace TarankoWebSite.Controllers
{
    public class AboutController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

TarankoWebSite/Controllers/ContactsController.cs
using Microsoft.AspNetCore.Mvc;

namespace TarankoWebSite.Controllers
{
    public class ContactsController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

TarankoWebSite/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using TarankoWebSite.Models;

namespace TarankoWebSite.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

TarankoWebSite/Controllers/ProjectsController.cs
using Microsoft.AspNetCore.Mvc;

namespace TarankoWebSite.Controllers
{
    public class ProjectsController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

TarankoWebSite/Controllers/ResumeController.cs
using Microsoft.AspNetCore.Mvc;

namespace TarankoWebSite.Controllers
{
    public class ResumeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

TarankoWebSite/Views/About/Index.cshtml
@{
    ViewData["Title"] = "About";
}

<div class="title_div">
    <p class="title1">I am</p>
    <p class="title2">Taras Taranko</p>
    <p class="title1">.NET developer.</p>
</div>
<div class="title-title_div container">
    <p class="title-title">About</p>
</div>
<div class="information_div container">
    <p class="information">My main goal is to develop high-quality solutions based on .NET for modern and demanding projects. I aspire to join a team that transforms great ideas into real products, contributing to innovative development.</p>
    <p class="information">I possess diverse expertise in .NET development, with skills in working with C#, ASP.NET, Entity Framework, and other key technologies. I have experience creating web applications, APIs, and interacting with databases.</p>
    <p class="information">I believe in a systematic approach to problem-solving. My work is rooted in thorough analysis and planning, accompanied by attention to detail. I am open to collaboration and continuously strive to enhance our processes.</p>
    <p class="information">I am studying for a bachelor's degree in "Software Engineering" at the Lviv Polytechnic National University. I gain new knowledge through online courses and self-study.</p>
    <p class="information">Outside of work, I enjoy playing the piano and playing computer games. Eager to explore new cultures and experiences, I am always ready to discover new places and explore the world.
    </p>
</div>
<script src="~/js/about-me.js" asp-append-version="true"></script>

TarankoWebSite/Views/Contacts/Index.cshtml
@{
    ViewData["Title"] = "Contacts";
}

<div class="title_div">
    <p class="title1">I am</p>
    <p class="title2">Taras Taranko</p>
    <p class="title1">.NET developer.</p>
</div>
<div class="title-title_div container">
    <p class="title-title">Contacts</p>
</div>
<div class="information_div container">
    <div class="contacts--hover-div-margin" id="contacts--hover-div">
        <a id="copyLink" class="contacts--information">tarankotaras.net@gmail.com</a>
    </div>
    <div class="contacts--hover-div-margin" id="contacts--hover-div">
        <a class="contacts--information" href="https://t.me/TarasTaranko" target="_blank">Telegram</a>
    </div>
    <div class="contacts--hover-div-margin" id="contacts--hover-div">
        <a class="contacts--information" href="https://instagram.com/taras_633?utm_source=qr&igshid=ZDc4ODBmNjlmNQ%3D%3D" target="_blank">Instagram</a>
    </div>
    <div class="contacts--hover-div-margin" id="contacts--hover-div">
        <a class="contacts--information" href="viber://chat?number=+380676023117" target="_blank">Viber</a>
    </div>
    <div class="contacts--hover-div-margin" id="contacts--hover-div">
        <a class="contacts--information" href="https://www.linkedin.com/in/taras-taranko-3b0a7b288" target="_blank">Linkedin</a>
    </div>  
</div>
<script src="~/js/contacts.js" asp-append-version="true"></script>

TarankoWebSite/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home";
}

<div class="home-page">
    <div class="hover-div-margin contacts-div-margin" id="hover-div">
        <a asp-area="" asp-controller="About" asp-action="Index" class="home-page__main-text1 appearance-annimation">Hello world.</a>
    </div>
    <div class="hover-div-margin" id="hover-div">
        <a asp-area="" asp-controller="Resume" asp-action="Index" class="home-page__main-text2  appearance-annimation">I am</a>
    </div>
    <div class="hover-div-margin" id="hover-div">
        <a asp-area="" asp-controller="Projects" asp-action="Index" class="home-page__main-text2  appearance-annimation">Taras Taranko</a>
    </div>
    <div class="hover-div-margin" id="hover-div">
        <a asp-area="" asp-controller="Contacts" asp-action="Index" class="home-page__main-text2  appearance-annimation">.NET developer</a>
    </div>
    <div class="bg-photo"></div>
</div>
<script src="~/js/home.js" asp-append-version="true"></script>

TarankoWebSite/Views/Projects/Index.cshtml
@{
    ViewData["Title"] = "Projects";
}

<div class="title_div">
    <p class="title1">I am</p>
    <p class="title2">Taras Taranko</p>
    <p class="title1">.NET developer.</p>
</div>
<div class="title-title_div container">
    <p class="title-title">Projects</p>
</div>
<div class="information_div container">
    <p class="information">Information about me...</p>
</div>
<script src="~/js/projects.js" asp-append-version="true"></script>

TarankoWebSite/Views/Resume/Index.cshtml
@{
    ViewData["Title"] = "Resume";
}

<div class="title_div">
    <p class="title1">I am</p>
    <p class="title2">Taras Taranko</p>
    <p class="title1">.NET developer.</p>
</div>
<div class="title-title_div container">
    <p class="title-title">Resume</p>
</div>
<div class="information_div container">
    <div class="resume--hover-div-margin" id="resume--hover-div">
        <a class="resume--information" href="./files/CV.pdf" download>My resume(pdf, 109kb)</a>
    </div>
    <div class="resume--hover-div-margin" id="resume--hover-div">
        <a class="resume--information" href="./files/CV.docx" download>My resume(docx, 109kb)</a>
    </div>
</div>
<script src="~/js/resume.js" asp-append-version="true"></script>

TarankoWebSite/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]</title>
    <link rel="stylesheet" href="~/css/index.css" asp-append-version="true" />
</head>
<body>
    <header class="header">
        <a class="logo" asp-area="" asp-controller="Home" asp-action="Index">T.T.</a>
    </header>
    <main>
        @RenderBody()
    </main>

    <footer>
    </footer>



    
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>